# This file was generated by GoReleaser. DO NOT EDIT.
class Browsh < Formula
  desc "The modern, text-based browser"
  homepage "https://www.brow.sh"
  version "1.6.4"

  if OS.mac?
    url "https://github.com/browsh-org/browsh/releases/download/v1.6.4/browsh_1.6.4_darwin_amd64.tar.gz"
    sha256 "1ca4cc0f1f9afd0d149a0f4e3db9ccc187479ab6fa125ab0be99de45a597ff65"
  elsif OS.linux?
  end

  def install
    bin.install "browsh"
  end

  def caveats; <<~EOS
    You need Firefox 57 or newer to run Browsh
  EOS
  end
end
