# This file was generated by GoReleaser. DO NOT EDIT.
class Browsh < Formula
  desc "The modern, text-based browser"
  homepage "https://www.brow.sh"
  version "1.6.3"

  if OS.mac?
    url "https://github.com/browsh-org/browsh/releases/download/v1.6.3/browsh_1.6.3_darwin_amd64.tar.gz"
    sha256 "fa6b57b2deffa445a42f94b98f2c56ecb1902928a821979bdac405b29fbdd6bd"
  elsif OS.linux?
  end

  def install
    bin.install "browsh"
  end

  def caveats; <<~EOS
    You need Firefox 57 or newer to run Browsh
  EOS
  end
end
