# This file was generated by GoReleaser. DO NOT EDIT.
class Browsh < Formula
  desc "The modern, text-based browser"
  homepage "https://www.brow.sh"
  url "https://github.com/browsh-org/browsh/releases/download/v1.5.2/browsh_1.5.2_darwin_amd64.tar.gz"
  version "1.5.2"
  sha256 "430fb7423c67172738bb011ab55a16ba1f4e37b5d82960cbcfd0b81492230454"

  def install
    bin.install "browsh"
  end

  def caveats; <<~EOS
    You need Firefox 57 or newer to run Browsh
  EOS
  end
end
